name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 Instance
        run: |
          echo "$private_key" > private_key && chmod 600 private_key
          ssh -vvv -o StrictHostKeyChecking=no -i private_key ${username}@${host} '
            cd /home/ubuntu/tws-portfolio &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin dev &&
            sudo npm i &&
            sudo npm run build &&
            sudo pm2 stop ./dist/index.js &&
            sudo pm2 start ./dist/index.js
          '
        env:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
