name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into EC2 Instance
      - uses: actions/checkout@v2
        env:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        
      - name: Deploy static site to S3 bucket
        run: |
          echo "$private_key" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${username}@$(host} '

            cd /home/ubuntu/tws-portfolio &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin dev &&
            sudo npm i &&
            sudo npm run build &&
            sudo pm2 stop ./dist/index.js &&
            sudo pm2 start ./dist/index.js
            '
